; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 112500
monitor_echo = yes
monitor_eol = LF
monitor_filters = send_on_enter

;esp-prog
;debug_tool = esp-prog
;upload_protocol = esp-prog
;debug_speed = 5000
;build_type = debug
;build_unflags = 
;    -Os
;    -O2
;
;build_flags =-O0
